apiVersion: v1
kind: Secret
metadata:
  name: {{ include "carapulse.fullname" . }}-config
  labels:
    {{- include "carapulse.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.json: {{ .Values.config | toJson | quote }}
